package client;

import org.jibble.pircbot.IrcException;
import org.jibble.pircbot.PircBot;

import java.io.IOException;

public class MessageRelay extends PircBot {

    static final String HOST_NAME = "irc.chat.twitch.tv";
    static final int PORT = 6667;

    static final String ROBSNEAKYMOUSE = "robSneakyMouse";
    static final String ROBDANGER = "robDANGER";

    private String channel;

    /**
     * Connect to a twitch IRC channel
     * @param channel the twitch account
     * @param username twitch username
     * @param oauth a password generated by twitch
     * @throws IOException Connection failed
     * @throws IrcException Connection failed
     */
    public MessageRelay(String channel, String username, String oauth) throws IOException, IrcException{
        this.channel = channel;
        this.setName(username);
        this.connect(HOST_NAME, PORT, oauth);
        this.joinChannel(channel);
    }

    public void sendMouse() {
        sendMessage(ROBSNEAKYMOUSE);
    }

    public void sendDanger() {
        sendMessage(ROBDANGER);
    }

    private void sendMessage(String message) {
        sendMessage(channel, message);
    }

    public void close() {
        SentFinalMessage.Disconnect(this);
    }

}
